name: Continuous Integration - Stratify ETL

on:
  push:
    branches:
      - main
      - sprint-3
jobs:
  test:
    name: Teste unitário
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install -r requirements.txt
    - name: Test with pytest
      run: python3 -m unittest discover -s tests
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Remote Server to Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Git Pull on Remote Server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
          cd apps/API_5SEM_ETL/
          git pull origin $(git rev-parse --abbrev-ref HEAD)
        EOF
